### ISSUE TITLE
Question: TLS certificate

### ISSUE THREAD

**Issue by xiekeyang** [cesanta/docker_auth#11]
@rojer ,
I read https://github.com/cesanta/docker_auth/issues/3 . But still have some confusion.
How do you generate TLS certificate?
If it is via `openssl genrsa` and `openssl req`? I don't think so.
Because the certificate's content is not accepted by docker distribution.
Could you please provide some example certificate?
Thanks a lot!

**Comment by DarkDirk** [comment]
Can you provide the config from your registry and the docker_auth? Both need the .pem file but only the docker_auth needs the .key.

**Comment by xiekeyang** [comment]
@DarkDirk 
I just use example config list in [examples/reference.yml](examples/reference.yml), as Distribution config.

```yml
auth:
    token:
          realm: "https://127.0.0.1:5001/auth"
          service: "Docker registry"
          issuer: "Acme auth server"
          rootcertbundle: "/path/to/server.pem"
```

And I didn't change and use original [examples/simple.yml ](examples/simple.yml ). It is OK?

**Comment by DarkDirk** [comment]
Sorry if I ask, but do you have the correct path in the distribution config? Mine looks like this
```
version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /data/registry/
    maintenance:
        uploadpurging:
            enabled: false
auth:
  token:
    realm: "https://localhost:5001/auth"
    service: "Docker registry"
    issuer: "Super auth server"
    rootcertbundle: "/go/src/github.com/docker/distribution/certs/server.pem"
http:
    addr: :5000
    secret: xxxxxxxxxx

```
My docker_auth config:
```
server:
  addr: ':5001'
  certificate: /ssl/server.pem
  key: /ssl/server.key
token:
  issuer: Super auth server
  expiration: 900
users:
  [....]
acl:
  [....]
```

Both server.pem are the same. Perhaps you can also find some more information here: https://docs.docker.com/registry/configuration/
