### ISSUE TITLE
docker_auth with load balancer

### ISSUE THREAD

**Issue by SydOps** [cesanta/docker_auth#122]
I currently work on the docker_auth to backend of openldap with load balancer, not sure if anyone did that before. 

The process will be: 

docker daemon (:443) --> ELB-1 (:5000)--> docker-registry(:5001)--> ELB -2 (:5001)--> docker_auth (:389) --> ELB-3 (:389) --> openldap

Currently ELB-1 has offload SSL certificate attached

I plan to install docker_auth certificate on ELB-2 to get the traffic offload on load balancer first, will docker_auth accepts insecure access?

**Comment by rojer** [comment]
if you don't specify `server.certificate` and `server.key`, listener will be opened without TLS.
in that case, you have to provide `token.certificate` and `token.key` to use for issuing tokens.

**Comment by SydOps** [comment]
Finally work it out, and prove it works in real environment.

```
**config/auth_config.yml**

server:
  addr: ":5001"

token:
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900
  certificate: "/certs/auth.crt"
  key: "/certs/docker_auth.key"
```
