### ISSUE TITLE
Failed to load config: could not parse config: yaml: control characters are not allowed with new version of Auth Server

### ISSUE THREAD

**Issue by naru014** [cesanta/docker_auth#125]
I was using the auth server stable version, but there was an issue for handling errors for ldaps which got fixed in the recent auth server release.
So I got the new image from docker hub and tried running it with my older working auth_config.yml.
But it is erroring out with
Failed to load config: could not parse config: yaml: control characters are not allowed
I tried running it with --v=2 for more information, but that also gave me the same issue.

I also tried with the a new yaml (content below) file which worked with the older image but gave the same error:
server:  # Server settings.
  # Address to listen on.
  addr: ":5001"
token:
  issuer: "Auth Service"
  expiration: 900
  notbefore: 300
  certificate: "/config/server.pem"
  key: "/config/server.key"
users:
  "": {}  # Allow anonymous (no "docker login") access.
acl:
  - match:
      account: ""
    actions: ["pull"]
    comment: "Anonymous can pull all images."

We want to use the new image to fix the error handling for ldap so please check and let us know.

**Comment by rojer** [comment]
github butchered formatting of the file. can you upload it as an attachment?

**Comment by naru014** [comment]
Attaching the yaml file 
[auth_config.zip](https://github.com/cesanta/docker_auth/files/397108/auth_config.zip)

**Comment by mv012004** [comment]
@rojer - Any update on this ? have you seen this, we ran into the same thing..!!

**Comment by rojer** [comment]
no, never. and the file looks normal to me at first glance. i'll take a look later.

**Comment by rojer** [comment]
i can't reproduce the issue - the exact file i extracted from zip attached to this issue is parsed just fine:
```I0803 22:54:31.515230   22667 main.go:163] docker_auth 20160725030348 build 20160725-030348/master@45388e5e
F0803 22:54:31.515515   22667 main.go:171] Failed to load config: failed to load token cert and key: open /config/server.pem: no such file or directory
```

it complains about being unable to open cert file, but this is already after the file has been parsed.

**Comment by naru014** [comment]
@rojer I pull the cesanta/docker_auth:stable from docker hub  and on my already existing node, stopped the older version of auth container running and then ran this container with the older config File and ran into this.  the older config file with the previous version works fine. So wondering what is it missing that is causing this.
Please correct me if my understanding is wrong, I can run the stable version of the auth image as a container with my older config file and it should just run fine right?
Any guidance on anything you feel is missing would be great

**Comment by rojer** [comment]
sorry, no idea. please verify your setup, because the config you sent parses just fine with current `:stable`:

```
$ docker pull cesanta/docker_auth:stable
stable: Pulling from cesanta/docker_auth
Digest: sha256:a00381737674b94ecf3f9d10168777d2424caec21378175f3110a08251cc2ba7
Status: Image is up to date for cesanta/docker_auth:stable
$ docker run --rm -it -v ~/Downloads/auth_config.yml:/auth_config.yml cesanta/docker_auth:stable --v=2 --alsologtostderr /auth_config.yml
I0804 16:40:09.054991       1 main.go:163] docker_auth 1.0 build 20160701-113058/1.0@f48ef319
F0804 16:40:09.064781       1 main.go:171] Failed to load config: failed to load token cert and key: open /config/server.pem: no such file or directory
```

**Comment by ppar** [comment]
Old ticket, but one silly way to get bit by this error is to run a `docker-compose.yml` file like:

```yaml
services:
  docker_auth:
    command: "/docker_auth/auth_server --v=2 --alsologtostderr"         # <--- !!
    image: "cesanta/docker_auth:1.13.0"
    volumes:
      - "/opt/docker-compose/docker_auth/auth_config.yml:/config/auth_config.yml:ro"
      -   ....
```

This will cause the auth_server to read its own binary as the config file, naturally causing parse errors. Also, if you're adding a `command` to specify those verbose flags, you need to explicitly pass the config file path in the args too. 

So you'll want:

```yaml
services:
  docker_auth:
    command: "--v=2 --alsologtostderr /config/auth_config.yml"
    image: "cesanta/docker_auth:1.13.0"
    volumes:
      - "/opt/docker-compose/docker_auth/auth_config.yml:/config/auth_config.yml:ro"
      - ...
```
