### ISSUE TITLE
unable to decode token response: invalid character '<'

### ISSUE THREAD

**Issue by ChipmunkV** [cesanta/docker_auth#174]
Auth:
```
server:
  addr: ":5001"
  certificate: "/var/lib/registry/domain.crt"
  key: "/var/lib/registry/domain.key"

token:
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900

users:
  # Password is specified as a BCrypt hash. Use htpasswd -B to generate.
  "admin":
    password: "$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC"  # badmin
  "test":
    password: "$2y$05$WuwBasGDAgr.QCbGIjKJaep4dhxeai9gNZdmBnQXqpKly57oNutya"  # 123

acl:
  - match: {account: "admin"}
    actions: ["*"]
    comment: "Admin has full access to everything."
  - match: {account: "test"}
    actions: ["pull"]
    comment: "User \"user\" can pull stuff."
# Access is denied by default.
```

Registry:
```
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  tls:
    certificate: /var/lib/registry/domain.crt
    key: /var/lib/registry/domain.key
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
auth:
  token:
    realm: https://reg.org.local:5006
    service: registry
    issuer: "Acme auth server"
    rootcertbundle: /var/lib/registry/domain.crt
```

```
$ docker login reg.org.local:5005
Username: 43
Password: 
Error response from daemon: Get https://reg.org.local:5005/v2/: unable to decode token response: invalid character '<' looking for beginning of value
$
```

Ports are fine (when auth is stopped - complains about a closed port). Config dirs are distinct. Keys and certificates are the same. Auth logs are empty. Username/Password don't matter.

What the auth server returns instead of token is this:
```
<h1>Acme auth server</h1>
```
