### ISSUE TITLE
[question][proposal] ability to set configuration in environment

### ISSUE THREAD

**Issue by fentas** [cesanta/docker_auth#175]
Is it/Would it possible to set the/parts of configuration in environment?
e.g.
```yaml
dockerauth:
    restart: always
    build: dockerauth/
    volumes:
      - ./dockerauth/config:/config:ro
      - /logs/dockerauth:/logs
      - dockerauth:/ssl
    environment:
      DOCKER_AUTH_USERS: >
        {
          "admin": {
            password: "$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC"  # badmin
          },
          "test": {
            password: "$(PW_TEST_USER)"
          }
        }
```
