### ISSUE TITLE
Get http://authserver.example.com:5000/v2/: Get https://authserver.example.com:5001/auth?account=admin&client_id=docker&offline_token=true&service=Docker+registry: Forbidden

### ISSUE THREAD

**Issue by zoranid** [cesanta/docker_auth#196]
```
 ubuntu

 16.04

1. How to pas verbose flag in docker-compose to get log info?

2. I get thje following response when I run docker-compose up

docker-compose: up

myuser@authserver:~/dev$ docker login authserver.example.com:5000
Username: admin
Password: *****

Get http://authserver.example.com:5000/v2/: Get https://authserver.example.com:5001/auth?account=admin&client_id=docker&offline_token=true&service=Docker+registry: Forbidden

docker-compose:

dockerauth:
  image: cesanta/docker_auth
  ports:
    - "5001:5001"
  volumes:
    - /home/myuser/dev/auth_server/config:/config:ro
    - /var/log/docker_auth:/logs
    - /home/myuser/dev/auth_server/ssl:/ssl

registry:
  image: registry:2
  ports:
    - "5000:5000"
  volumes:
    - /home/myuser/dev/auth_server/ssl:/ssl
    - /home/myuser/dev/docker_registry/data:/var/lib/registry
  environment:
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
    - REGISTRY_AUTH=token
    - REGISTRY_AUTH_TOKEN_REALM=https://authserver.example.com:5001/auth
    - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
    - REGISTRY_AUTH_TOKEN_ISSUER="Auth Service"
    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/server.pem

auth_config.yml

server:  # Server settings.
  # Address to listen on.
  addr: ":5001"
  # TLS certificate and key.
  certificate: "/ssl/server.pem"
  key: "/ssl/server.key"

token:  # Settings for the tokens.
  issuer: "Auth Service"  # Must match issuer in the Registry config.
  expiration: 900


# Static user map. 
users:
  # Password is specified as a BCrypt hash. Use htpasswd -B to generate.
  "admin":
    password: "$2y$05$B.x046DV3bvuwFgn0I42F.W/SbRU5fUoCbCGtjFl7S33aCUHNBxbq"
  "": {}  # Allow anonymous (no "docker login") access.

acl:
  # Admin has full access to everything.
  - match: {account: "admin"}
    actions: ["*"]
  # User "test" has full access to ubuntu image but nothing else.
  - match: {account: "test", name: "ubuntu"}
    actions: ["*"]
  # All logged in users can pull all images.
  - match: {account: "/.+/"}
    actions: ["pull"]
  # Anonymous users can pull "hello-world".
  - match: {account: "", name: "hello-world"}
    actions: ["pull"]
  # Access is denied by default.
```
