### ISSUE TITLE
Incorrect processing of ACLs

### ISSUE THREAD

**Issue by henti** [cesanta/docker_auth#198]
using 1.3 with github_auth (Thank you for latest release), however the ACL processing seems to be broken. 

I built the following ACL. 

```
acl:
  - match: {account: "/.+/", type: "registry", name: "catalog"}
    actions: ["*"]
    comment: "Logged in users can query the catalog."
  - match: {account: "/.+/", type: "repository", name: "scratch/*"}
    actions: ["*"]
    comment: "Logged in users have full access to images that are in scratch/* namespace"
  - match: {account: "henti"}
    actions: ["push"]
    comment: "User henti can push"
```

My understanding according to reference.yml is that this will give all Logged in users access to read the catalog, full access to scratch/* namespace and I can push anywhere. 

In practise, only the last ACL is applied. When logged in, I can list the repos but not the tags, cannot push to scratch/* or at all actually. The only way I can read tags and push is if I change ["push"] to ["*"]

It's possible I misunderstand the reference.yml, if so, please clarify. 

Henti
