### ISSUE TITLE
Pattern matching for "name"?

### ISSUE THREAD

**Issue by deitch** [cesanta/docker_auth#20]
A very common pattern is to allow anyone to access their own named repository. Thus, if I can successfully authenticate as "jimd", then I should be able to access a repo that is at `jimd/`.

The current config (seems) not to support it. It should be fairly simple to do the following, though:

````yml
acl:
  # All logged in users can access their own images 
  - match: {account: "/^(.+)$/", name: "/^\1\/*"}
    actions: ["*]
  # alternate pattern, depending on your regexp engine
  - match: {account: "/^(.+)$/", name: "/^\$1\/*"}
    actions: ["*]
````

**Comment by rojer** [comment]
this seems reasonable. i will review a PR implementing this, otherwise it'll need to wait until i have spare time.

**Comment by rojer** [comment]
wait... this always assumes capture groups come from account, a generic solution would allow capturing anywhere. but would introduce dependencies. how about instead we allow expansion of any field from AuthRequestInfo, which contains:
```go
type AuthRequestInfo struct {
	Account string
	Type    string
	Name    string
	Service string
	Actions []string
}
```
you could then use `${Account}` or something like that, without using regex capturing.

**Comment by deitch** [comment]
What are the meanings of the other fields? 

* `Account`: OK, authenticated user
* `Type`: what is this?
* `Name`: is this the rep in the request, e.g. `deitch/myapp`?
* `Service`: is this the `service` in the request, e.g. `hub.docker.io` or `my.private.reg:5000`?
* `Actions`: I guess these are `["push","pull"]`

**Comment by rojer** [comment]
Type comes from the request, but currently is always "repository"
Name is the name of the repo, i.e. image (i find this repository/image name duality confusing)
Service also comes from the token request and is configured in registry config's `auth.token.service` parameter. Thus, even today you could have two completely different registries talking to the same auth server and be able to write completely distinct set of acls for them by matching on service.
Actions are the "scopes" requested. since 1.8 they are always push and pull.

**Comment by deitch** [comment]
Got it. And these are the same keys that are used in the JSON object under `match`?

**Comment by rojer** [comment]
yes

**Comment by deitch** [comment]
So then there would be special variables in the match, then?

````yml
acl:
  # All logged in users on any domain can access their own images 
  - match: {account: "/^(.+)$/", name: "${account}"}
    actions: ["*]
  # All logged in users on foo.reg can access their own images 
  - match: {account: "/^(.+)$/", service: "foo.reg", name: "${account}"}
    actions: ["*]
````

That makes sense. Let's start with that. At some point it would need to be more powerful, allowing regex within the variable, but one step at a time.
