### ISSUE TITLE
Unable to connect to Azure's Cosmos DB (MongoDB)

### ISSUE THREAD

**Issue by techknowlogick** [cesanta/docker_auth#205]
Azure runs Cosmos DB on a non-standard MongoDB port, and requires SSL. Due to these two things docker_auth is unable to connect to the MongoDB server.

Example of the config block that I attempted to use to connect so far:
```
mongo_auth:
  dial_info:
    addrs: ["docker-registry-auth-test.documents.azure.com:10255"]
    timeout: "10s"
    database: "docker_auth"
    username: "docker-registry-auth-test"
    password: "abcd1234"
  collection: "users"
```
Azure provides a connection string similar to: `mongodb://docker-registry-auth-test:abcd1234@docker-registry-auth-test.documents.azure.com:10255/?ssl=true`
