### ISSUE TITLE
SQL authn

### ISSUE THREAD

**Issue by Ouwen** [cesanta/docker_auth#224]
Figured it would be nice to have a SQL option for Auth. #223 

Adding the following yaml block will connect to a SQL user, password, labels store

```yaml
sql_auth:
  connection:
    # only postgres and mysql drivers are currently supported
    driver: "postgres"
    # data_source_name is driver specific and can be an env var
    data_source_name: "postgres://postgres:password@localhost:5435/postgres?&sslmode=disable"
  table: "users"
  user_column: "username"
  password_column: "password"
  labels_column: "labels"
```

The `data_source_name` can be an environmental variable specified by `$MY_DATA_SOURCE_NAME`
or `${MY_DATA_SOURCE_NAME}`

If you already have an existing table of users you can map them by mapping 
 - a `text` column of the table to `user_column`
 - a `text` column of the table to `password_column`
 - a `json` column of the table to `labels_column`
