### ISSUE TITLE
Applying labels to static users

### ISSUE THREAD

**Issue by superstator** [cesanta/docker_auth#229]
Forgive me if I've missed something obvious, but I am trying to apply group labels to users in a static config. The reference examples don't seem to cover this, and my guesses haven't panned out so far. Right now I have a config that looks something like this:

```
    users:
      "cool_user":
        password: "<snip>"
        labels:
          group:
          - "internal_users"
    
    acl:
      - match: {labels: {"group": "internal_users"}}
        actions: ["pull"]
```

I'm able to login as `cool_user`, but I cannot pull anything. I'm guessing the problem is with the user definition as opposed to the ACL, but I'd be grateful if somebody could point me the right direction.

**Comment by carsonoid** [comment]
I hate to say it, but it works for me. Here is a full `auth_config.yml` that I tested with and got the expected results:

```
server:  # Server settings.
  # Address to listen on.
  addr: ":4433"
  # TLS certificate and key.
  certificate: "/ssl/server.pem"
  key: "/ssl/server.key"

token:  # Settings for the tokens.
  issuer: "Auth Service"  # Must match issuer in the Registry config.
  expiration: 900

users:
  external_user:
    password: "$2y$05$jQanzRvEYJulyXwOCGBJuunyu1jlCZwqOe8bQIIE/yGdyOB1hwds2" # test
  internal_user:
    password: "$2y$05$jQanzRvEYJulyXwOCGBJuunyu1jlCZwqOe8bQIIE/yGdyOB1hwds2" # test
    labels:
      group:
      - "internal_users"

# Static acls that will always exist regardless of mongo availability
acl:
  - match:
      labels:
        group: "internal_users"
    actions: ["pull"]
```

Test:

```
$ docker login localhost -u internal_user -p test
Login Succeeded
$ docker pull localhost/busybox
Using default tag: latest
latest: Pulling from busybox
0ffadd58f2a6: Already exists 
Digest: sha256:712bae289005bed2f7ab27f622655150d2035bf3804d42130566149f685ce18c
Status: Image is up to date for localhost/busybox:latest
$ docker login localhost -u external_user -p test
Login Succeeded
$ docker pull localhost/busybox
Using default tag: latest
Error response from daemon: repository localhost/busybox not found: does not exist or no pull access
```
