### ISSUE TITLE
panic: non-positive interval for NewTicker

### ISSUE THREAD

**Issue by bykvaadm** [cesanta/docker_auth#236]
Hi! i've got this error, trying to connect docker_auth to mongodb in docker-compose:

```
mongo_1     | 2018-07-12T10:12:11.652+0000 I NETWORK  [listener] connection accepted from 172.18.0.4:34894 #15 (1 connection now open)
cesanta_1   | panic: non-positive interval for NewTicker
cesanta_1   | 
cesanta_1   | goroutine 1 [running]:
cesanta_1   | time.NewTicker(0x0, 0xc4200a96c0)
cesanta_1   | 	/usr/local/go/src/time/tick.go:23 +0x1a1
cesanta_1   | github.com/cesanta/docker_auth/auth_server/authz.NewACLMongoAuthorizer(0xc420188c60, 0xec8a78, 0xc42019a000, 0xeaafe8, 0xc4201fdbd8)
cesanta_1   | 	/go/src/github.com/cesanta/docker_auth/auth_server/authz/acl_mongo.go:50 +0x61
cesanta_1   | github.com/cesanta/docker_auth/auth_server/server.NewAuthServer(0xc4200dadc0, 0x30, 0xc4201fddd8, 0x3)
cesanta_1   | 	/go/src/github.com/cesanta/docker_auth/auth_server/server/server.go:62 +0xa3b
cesanta_1   | main.ServeOnce(0xc4200dadc0, 0x7ffc1805ff64, 0x17, 0xc42018d050, 0xa7e1c0, 0x1, 0xc42018d050)
cesanta_1   | 	/go/src/github.com/cesanta/docker_auth/auth_server/main.go:47 +0x18d
cesanta_1   | main.(*RestartableServer).Serve(0xc4201fdf48, 0xc4200dadc0)
cesanta_1   | 	/go/src/github.com/cesanta/docker_auth/auth_server/main.go:97 +0x4e
cesanta_1   | main.main()
cesanta_1   | 	/go/src/github.com/cesanta/docker_auth/auth_server/main.go:177 +0x249
cesanta_1   | panic: non-positive interval for NewTicker
mongo_1     | 2018-07-12T10:12:11.700+0000 I NETWORK  [conn15] end connection 172.18.0.4:34894 (0 connections now open)
registry_cesanta_1 exited with code 2
```

Docker-compose:

```
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    volumes:
    - ./mongo/data:/data/db
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
  cesanta:
    depends_on:
    - mongo
    - registry
    image: cesanta/docker_auth
    ports:
    - 5001:5001
    volumes:
    - ./ssl:/ssl
    - ./cesanta/cesanta_config:/config
    - ./cesanta/cesanta_logs:/logs
  registry:
    restart: always
    image: registry:2
    ports:
    - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/certificate.pem
      REGISTRY_HTTP_TLS_KEY: /certs/key.pem
    volumes:
    - ./ssl:/certs
    - ./registry/registry_data:/var/lib/registry
    - ./registry/registry_config:/etc/docker/registry/config.yml
```

config:

```
server:
  addr: ":5001"
  certificate: "/ssl/certificate.pem"
  key: "/ssl/key.pem"

token:
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900

mongo_auth:
  dial_info:
    addrs: ["mongo:27017"]
    timeout: "10s"
    database: "API"
    username: ""
    password_file: ""
    enable_tls: false
  collection: "users"    

acl_mongo:
  dial_info:
    addrs: ["mongo:27017"]
    timeout: "10s"
    database: "API"
    username: ""
    password_file: ""
    enable_tls: false
  collection: "acl"
cache_ttl: "10s"
```

Could u please tell me what i'm doing wrong?  Without mongo int works fine.
docker_auth version: 1.3.1,latest
