### ISSUE TITLE
order of acls matters!

### ISSUE THREAD

**Issue by jaguardev** [cesanta/docker_auth#237]
this
```
acl:
  - match: {account: "/.+/", name: "${account}/*"}
    actions: ["*"]
    comment: "Logged in users have full access to images that are in their 'namespace'"
  - match: {account: "/.+/"}
    actions: ["pull"]
    comment: "Logged in users can pull all images."
  - match: {account: "jenkins"}
    actions: ["*"]
    comment: "jenkins has full access to everything."
```

is not the same as
```
acl:
  - match: {account: "jenkins"}
    actions: ["*"]
    comment: "jenkins has full access to everything."
  - match: {account: "/.+/", name: "${account}/*"}
    actions: ["*"]
    comment: "Logged in users have full access to images that are in their 'namespace'"
  - match: {account: "/.+/"}
    actions: ["pull"]
    comment: "Logged in users can pull all images."
```
spent a few hours to catch this. maybe update documentation with a note "acl order matters"?
