### ISSUE TITLE
Docker push causes unauthorized: authentication required when pushing

### ISSUE THREAD

**Issue by leonardochaia** [cesanta/docker_auth#240]
Hi, **this is not an issue**. Just wanted to share this since it was hard to find.
I'm pushing this layer which weights 14gb. I'm getting this error after the layer finishes pushing:
```powershell
docker -D push foo.bar/repo:tag
The push refers to repository [foo.bar/repo]
Pushing [==================================================>]  13.99GB
Layer already exists
Layer already exists
Layer already exists
Layer already exists
Layer already exists
Layer already exists
Layer already exists
unauthorized: authentication required
```

I found some curious logs on the registry:
```
time="2018-07-26T22:22:16Z" level=info msg="token not to be used after 2018-07-26 22:16:58 +0000 UTC - currently 2018-07-26 22:22:16.762869048 +0000 UTC"
time="2018-07-26T22:22:16Z" level=warning msg="error authorizing context: invalid token"
```

I believe that when the docker client attempts to finish the operation the token is expired, which leaded me to increase the `expiration`  on the auth config, which I had copied from the examples with a default of 900.
```yaml
token:  # Settings for the tokens.
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900
```

Thanks.
Leo.
