### ISSUE TITLE
google_auth + static user map

### ISSUE THREAD

**Issue by trollr** [cesanta/docker_auth#243]
At the moment I create a helm chart for docker_auth to deploy it with ease in a k8s cluster (I will later 
 publish it in incubator repo). However I have an issue with google auth + static user map for technical users (eg. build systems without oauth account). Is it possible to use both ways? 

That's my current config

```
server:
  addr: ":5001"

users:
  "builder":
    password: xxx
  
token:  
  issuer: XXX auth server 
  expiration: 900
  certificate: /certs/token.pem
  key: /certs/token.key
google_auth:
  domain: xxx.de
  client_id: xxx
  client_secret: xxx
  token_db: "/data/google_token_db.ldb"
  http_timeout: 10

acl:
  - actions:
    - push
    - pull
    comment: Logged in users can everything
    match:
      account: /.+/
```
