### ISSUE TITLE
Authentication failing with file not found

### ISSUE THREAD

**Issue by ankushChatterjee** [cesanta/docker_auth#278]
This is what I am seeing in logs when `docker login <server_name>`
```
dockerauth_1  | E0501 17:53:40.280683       1 ext_auth.go:97] Ext command error: 3 cmd run error: fork/exec /extensions/authentication: no such file or directory

dockerauth_1  | E0501 17:53:40.280851       1 server.go:278] {admin:***@172.20.0.1:42174 []}: authn #1 returned error: bad return code from command: 3
```
According to the error, /extensions/authentication does not exist, but on using /bin/sh on the container, one can find the files in extensions folder (in the correct path).
The extensions folder is a mounted volume in docker. I am pasting the extAuth.yml and my docker-compose.yml for more clarity.

extAuth.yml
```
server:
  addr: ":5001"
  certificate: "/ssl/domain.crt"
  key: "/ssl/domain.key"

token:
  issuer: "Auth Service"  
  expiration: 900

acl:
  - match:
      account: "admin"
    actions: ['push']

ext_auth:
  command: "/extensions/authentication"  
  args: [""]

ext_authz:
  command: "/extensions/authorization"
  args: [""]
```
docker-compose.yml
```
version: "2.3"
services:
 registry:
  image: registry:2
  ports:
    - "5000:5000"
  volumes:
    - ./conf/ssl:/ssl
    - ./data:/data
  restart: always
  environment:
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
    - REGISTRY_AUTH=token
    - REGISTRY_AUTH_TOKEN_REALM=https://example.docker.com:5001/auth
    - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
    - REGISTRY_AUTH_TOKEN_ISSUER="Auth Service"
    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/domain.crt
    - REGISTRY_HTTP_TLS_CERTIFICATE=/ssl/domain.crt
    - REGISTRY_HTTP_TLS_KEY=/ssl/domain.key
 dockerauth:
   image: cesanta/docker_auth
   ports:
     - "5001:5001"
   volumes:
     - ./:/config
     - ./conf/ssl:/ssl
     - ./extensions:/extensions
   command: -alsologtostderr=true -log_dir=/logs /config/extAuth.yml
   restart: always
```
Is it a problem in the configuration or the setup side? 
One more thing to note is in ext_auth.go:82
	`glog.V(2).Infof("%s %s -> %d %s", cmd.Path, cmd.Args, es, output)`
I am not able to see any logs for this line... maybe this would provide some clarity on what path exactly being used.

In my console, the response after executing login is
`Error response from daemon: Get https://localhost:5000/v2/: received unexpected HTTP status: 500 Internal Server Error`
