### ISSUE TITLE
connect: connection refused

### ISSUE THREAD

**Issue by sb2050** [cesanta/docker_auth#299]
Good day,
after I set up the registry and docker_aut I get the message
`connect: connection refused`
Does anyone know what the reason is?
I have removed domain, ip, user and password from the configs

Console Output:
```
docker login domain
Username: user
Password: 
Error response from daemon: Get https://domain/v2/: Get https://localhost:5001/auth?account=user&client_id=docker&offline_token=true&service=Docker+registry: dial tcp [::1]:5001: connect: connection refused
```

Console docker-registry:
```
docker-registry    | time="2021-02-03T22:15:39.247861797Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.2 http.request.host=`domain http.request.id=3d74d943-d9c6-4608-a865-2db481aa7616 http.request.method=GET http.request.remoteaddr=ip http.request.uri="/v2/" http.request.useragent="docker/20.10.2 go/go1.13.15 git-commit/8891c58 kernel/4.19.128-microsoft-standard os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.2 \(windows\))"
docker-registry    | ip - - [03/Feb/2021:22:15:39 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/20.10.2 go/go1.13.15 git-commit/8891c58 kernel/4.19.128-microsoft-standard os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.2 \\(windows\\))"
```

docker-compose:
```
services:
  docker-registry:
    image: registry:latest
    container_name: docker-registry
    ports:
      - 443:443
    restart: always
    volumes:
      - /mnt/volume/docker-registry/data/:/data/
      - /mnt/volume/docker-registry/auth/:/auth/
      - /mnt/volume/docker-registry/certs/:/certs/
    environment:
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: https://localhost:5001/auth
      REGISTRY_AUTH_TOKEN_SERVICE: "Docker registry"
      REGISTRY_AUTH_TOKEN_ISSUER: "Acme auth server"
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/server.pem
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain/domain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/domain/domain.key
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data

  docker-auth:
    image: cesanta/docker_auth:1
    container_name: docker-auth
    ports:
      - 5001:5001
    restart: always
    volumes:
      - /mnt/volume/docker-auth/config:/config/
      - /mnt/volume/docker-auth/logs/:/logs/
      - /mnt/volume/docker-auth/certs/:/certs/
```

auth_config:
```
server:
  addr: ":5001"
  certificate: "/certs/server.pem"
  key: "/certs/server.key"

token:
  issuer: "Acme auth server"
  expiration: 900

users:
  "user":
    password: "password"

acl:
  - match: {account: "user"}
    actions: ["*"]
    comment: "Admin has full access to everything."
  - match: {}
    actions: ["pull"]
    comment: "All can pull stuff."
```
