### ISSUE TITLE
Mongodb 5.0 Failed to create auth server: saslContinue.mechanism' is an unknown field.

### ISSUE THREAD

**Issue by joda01** [cesanta/docker_auth#315]
When trying to authenticate against a mongodb 5.0.1 database I get the error code:

```
main.go:64] Failed to create auth server: server returned error on SASL authentication step: BSON field 'saslContinue.mechanism' is an unknown field.
```
With same settings no problem with mongodb 4.

```
    mongo_auth:
      # Essentially all options are described here: https://godoc.org/gopkg.in/mgo.v2#DialInfo
      dial_info:
        # The MongoDB hostnames or IPs to connect to.
        addrs: ["mongodbroutersvc.db.svc.cluster.local:27017"]
        # The time to wait for a server to respond when first connecting and on
        # follow up operations in the session. If timeout is zero, the call may
        # block forever waiting for a connection to be established.
        # (See https://golang.org/pkg/time/#ParseDuration for a format description.)
        timeout: "10s"
        # Database name that will be used on the MongoDB server.
        database: "auth"
        # The username with which to connect to the MongoDB server.
        username: "docker"
        # Path to the text file with the password in it.
        password_file: "/passwd/mongodbdockerregpassword"
        # Enable TLS connection to MongoDB (only enable this if your server supports it)
        enable_tls: false
        # Name of the collection in which ACLs will be stored in MongoDB.
      collection: "docker"
      # Unlike acl_mongo we don't cache the full user set. We just query mongo for
      # an exact match for each authorization
```
