### ISSUE TITLE
ldap_auth memberOf label can't match to actual group DN

### ISSUE THREAD

**Issue by lgprobert** [cesanta/docker_auth#332]
By following the ldap group label feature in "references" configuration document in project, I can't make it matched to the sample ACL rule.

The LDAP config is like this:
```
ldap_auth:
  addr: <ldap_address>
  initial_bind_as_user: true
  bind_dn: "uid=${account},ou=people,<base_dn>"
  base: <base_dn>
  filter: (&(uid=${account})(objectClass=person))
  labels:
    groups:
      attribute: memberOf
acl:
  - match: 
      name: "p/${labels:groups}/*"
    actions: ["push", "pull"]
    comment: "Users can push to projects they are assigned to"
```

When running the above config, the log has below messages:

```
authserver_1  | I0105 02:17:50.893465       1 ldap_auth.go:237] Searching...basedDN:<base_dn>, filter:(&(uid=user1)(objectClass=person))
authserver_1  | I0105 02:17:50.894510       1 ldap_auth.go:264] Entry memberOf = cn=qa,ou=group,<base_dn>
authserver_1  | I0105 02:17:50.895251       1 server.go:317] Authn LDAP user1 -> true, map[groups:[cn=qa,ou=group,<base_dn>]], <nil>
authserver_1  | I0105 02:17:50.895528       1 server.go:339] Authz static ACL {user1 pull repository qa/alpine} -> [], did not match any rule
authserver_1  | W0105 02:17:50.895548       1 server.go:351] {user1 pull repository qa/alpine} did not match any authz rule
authserver_1  | I0105 02:17:50.901360       1 server.go:429] New token for {user1:***@192.168.56.20:60114 [{repository  qa/alpine [pull]}]} map[groups:[cn=qa,ou=group,<base_dn>]]: {"iss":"Example Inc.","sub":"user1","aud":"Docker registry","exp":1641349970,"nbf":1641349060,"iat":1641349070,"jti":"5486817126750104164","access":[{"type":"repository","name":"qa/alpine","actions":[]}]}
```

I feel the matched result from `memberOf` is a full DN, like: `cn=qa,ou=group,dc=example,dc=com`, but the `{labels:groups}` expects a group name `qa` only so that it always find no match.

Not sure how can I achieve a working config in regarding to this sample config.

Appreciate for any help and hints.

Thanks

**Comment by lgprobert** [comment]
Just dig out a line in `reference.yml` that says:

```
groups:
      attribute: memberOf
      # Special handling to simplify the values to just the common name
      parse_cn: true
```

I feel that is the setting I missed and now I get one step closer to the solution. Adding the line still results error, but the message is a bit different:

```
authserver_1  | I0105 03:48:13.279840       1 server.go:317] Authn LDAP user1 -> true, map[groups:[qa]], <nil>
authserver_1  | I0105 03:48:13.279973       1 server.go:339] Authz static ACL {user1 pull repository qa/alpine} -> [], did not match any rule
```
The problem lies on `map[groups:[qa]]` matching to `name: "p/${labels:groups}/*"` at  ACL rule results no match. 

Anything am I missing?

Thanks
