### ISSUE TITLE
unable to decode token response: invalid character '<'

### ISSUE THREAD

**Issue by ffeldbauer** [cesanta/docker_auth#338]
Hey,
I'm trying to set up a private docker registry with docker_auth but it is not working.

When trying to login to the docker registry I get the following error:
```
Error response from daemon: Get https://myserver/v2/: unable to decode token response: invalid character '<' looking for beginning of value
```

My docker_auth config:
```
server:
  addr: ":5001"
  path_prefix: "/auth"
  certificate: "/config/auth.crt"
  key: "/config/auth.key"

token:
  issuer: "docker_auth - aa8AhshuoCh5eade"
  expiration: 900
```
My registry config
```
auth:
  token:
    realm: https://myserver/auth
    service: myserver:443
    issuer: "docker_auth - aa8AhshuoCh5eade"
    rootcertbundle: /config/auth.crt
```
Docker registry as well as docker_auth are located behind a reverse proxy using nginx
```
     location /v2/ {
         if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
           return 404;
         }
         add_header 'Docker-Distribution-Api-Version' $docker_distribution_api_version always;
 
         proxy_set_header HOST $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 
         proxy_pass http://registry:5000;
         proxy_http_version 1.1;
 
         fastcgi_read_timeout 60000;
         fastcgi_send_timeout 60000;
         send_timeout 60000;
         proxy_read_timeout 60000;
         proxy_send_timeout 60000;
     }
 
     location /auth {
         proxy_pass https://auth:5001/auth;
         proxy_set_header HOST $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_ssl_trusted_certificate /etc/nginx/ssl/joomla.pem;
         proxy_read_timeout 900;
     }
```
Not sure what I'm doing wrong. Hope someone can help me.
Cheers,
Florian
