### ISSUE TITLE
auth_token failed behind nginx

### ISSUE THREAD

**Issue by scorpinxia** [cesanta/docker_auth#355]
I want deploy registry and auth service behind nginx like below compose.yml

`  
```
nginx:
    container_name: nginx
    image: nginx:1.19-security
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf
      - ....
    ports:
      - '443:443'
      
registry:
    container_name: registry
    restart: always
    image: registry:2.7.1-security
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_AUTH_TOKEN_REALM: https://DOMAIN/auth
      REGISTRY_AUTH_TOKEN_SERVICE: container_registry
      REGISTRY_AUTH_TOKEN_ISSUER: test_auth_server
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /home/RootCA.crt
    volumes:
      - ./registry:/var/lib/registry
      - ./nginx/cert/auth.crt:/home/RootCA.crt

  registry_auth:
    container_name: registry_auth
    restart: always
    image: docker_auth:1.10
    command:
      - --v=2
      - --alsologtostderr
      - /config/auth_config.yml
    volumes:
      - ./registry_auth/auth_config.yml:/config/auth_config.yml
      - ./nginx/cert/auth.crt:/home/RootCA.crt
      - ./nginx/cert/auth.key:/home/RootCA.key
    
```
`

when I use docker client to visit it , I see generate token from log
`I0117 13:44:54.901993       1 server.go:429] New token for {admin:***@10.4.1.234:48354 []} map[]: {"iss":"auth_server","sub":"admin","aud":"container_registry","exp":1673963994,"nbf":1673963084,"iat":1673963094,"jti":"6143712233580057810","access":[]}` 

but  it auth failed 

`FATA[0011] failed to call rh.Authorizer.AddResponses: server message: invalid_token: authorization failed`

if I change to use a host port,It works，I think it because remoteAddress are bind to token, but I cannot change nginx remote_address, nginx config like below
`    location /auth {
      proxy_pass                          http://docker-registry-auth;
      proxy_set_header  Host              $http_host;   # required for docker client's sake
      proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
      proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header  X-Forwarded-Proto $scheme;
      proxy_read_timeout                  90;
      proxy_redirect                      off;
    }`

**Is there any way to use container port (not host port just behind nginx  443 )**
