### ISSUE TITLE
ACL for allowing anonymous access to catalog

### ISSUE THREAD

**Issue by clarktlaugh** [cesanta/docker_auth#39]
I would like to setup my ACL to allow anonymous access to the catalog, as well as pulling all images.  Could someone help me with how to specify that?

Here's what I am currently using, but it isn't working:

```
acl:
  # Admin has full access to everything.
  - match: {account: "admin"}
    actions: ["*"]
  # User "public" can pull stuff.
  - match: {account: "public"}
    actions: ["pull"]
  # Trying to allow anonymous to access the catalog, pull stuff
  - match: {account: ""}
    actions: ["pull"]
  # Access is denied by default.
```

This is what I get when I try to hit ```https://my-registry.server.org/v2/_catalog``` in a web browser:
```
{"errors":[{"code":"UNAUTHORIZED",
"message":"access to the requested resource is not authorized",
"detail":[{"Type":"registry","Name":"catalog","Action":"*"}]}]}
```

**Comment by kwk** [comment]
Try to access your registry's catalog using curl `curl -v https://YOUR_REGISTRY:5000/v2/_catalog` and inspect the `Www-Authenticate` header in the response from the registry. It should give you a hint on what permissions are required to access the `_catalog` resource.

I've setup a docker-registry, authentication and LDAP server ready to use if you want to try out various scenarios: https://github.com/kwk/docker-registry-setup. At the bottom of the README I also write about manually querying the registry and then the auth server.

**Comment by rojer** [comment]
acl is the authorization part, i.e. when we know who are we talking to.
the part where we authenticate precedes that.
you didn't paste the `users` part of the config, but basically this line is crucial for allowing anonymous access:
```"": {}  # Allow anonymous (no "docker login") access.```

this is from https://github.com/cesanta/docker_auth/blob/master/examples/reference.yml

**Comment by clarktlaugh** [comment]
Sorry -- this is the users: and acl: portion of my config:

```
users:
  # Password is specified as a BCrypt hash. Use htpasswd -B to generate.
  "admin":
    password: "$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC"  # badmin
  "public":
    password: "$2y$05$WuwBasGDAgr.QCbGIjKJaep4dhxeai9gNZdmBnQXqpKly57oNutya"  # 123
  "" : {}  # anonymous

acl:
  # Admin has full access to everything.
  - match: {account: "admin"}
    actions: ["*"]
  # User "user" can pull stuff.
  - match: {account: "public"}
    actions: ["pull"]
  # Anonymous access to the catalog
  - match: {account: ""}
    actions: ["pull"]
  # Access is denied by default.
```

**Comment by rojer** [comment]
can you run the server with --v=2?
it should be clear why request is being rejected.
if not, post the log here.

**Comment by dreamcwli** [comment]
I have the same problem here. After playing around for a bit I found that registry will always ask for bearer token when accessing catalog. Related bugs seem to exist in registry rather than in docker_auth.

**Comment by jeffrey4l** [comment]
I have the same issue too. 

configuration file 
```
server:
  addr: ":5001"
  certificate: "/config/cert.pem"
  key: "/config/cert.key"

token:
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900

users:
  # Password is specified as a BCrypt hash. Use htpasswd -B to generate.
  "admin":
    password: "$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC"  # badmin
  "test":
    password: "$2y$05$WuwBasGDAgr.QCbGIjKJaep4dhxeai9gNZdmBnQXqpKly57oNutya"  # 123
  "": {}

acl:
  - match: {account: ""}
    actions: ["*"]
    comment: "Anonymous users can pull everything."
  - match: {account: "admin"}
    actions: ["*"]
    comment: "Admin has full access to everything."
  - match: {account: "user"}
    actions: ["pull"]
    comment: "User \"user\" can pull stuff."
  # Access is denied by default.
```

```
docker pull <domain>/kolla/centos-source-elasticsearch:3.0.1

Please login prior to pull:
Username (admin): 
Password: 
Error: Password Required
```

docker_auth logs

```
I1113 00:06:39.798408       1 server.go:368] Auth request: {admin:***@172.17.0.1:52122 [{repository kolla/centos-source-elasticsearch [pull]}]}
I1113 00:06:39.807334       1 server.go:215] Authn static admin -> false, map[], <nil>
W1113 00:06:39.807369       1 server.go:376] Auth failed: {admin:***@172.17.0.1:52122 [{repository kolla/centos-source-elasticsearch [pull]}]}

```

**Comment by jeffrey4l** [comment]
after removed following lines in the configuration file, it works. 

```
  - match: {account: "user"}
    actions: ["pull"]
    comment: "User \"user\" can pull stuff."
```

**Comment by ZirkPrime** [comment]
I am having the same issue originally described (trying to allow anonymous access to catalog). When trying to use curl to get the catalog contents, I get the following response:
```
$ curl -k https://my-registry.server.com:5000/v2/_catalog
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}
```
I am following the below example from https://github.com/cesanta/docker_auth/blob/master/examples/reference.yml
```
  - match: {account: "/.+/", type: "registry", name: "catalog"}
    actions: ["*"]
    comment: "Logged in users can query the catalog."
```
except I have modified it to be anonymous access instead of any logged in user, my exact config file is below.
```
server:  # Server settings.
  # Address to listen on.
  addr: ":5001"
  # TLS certificate and key.
  certificate: "/ssl/domain.crt"
  key: "/ssl/domain.key"

token:  # Settings for the tokens.
  issuer: "Auth Service"  # Must match issuer in the Registry config.
  expiration: 900


# Static user map. 
users:
  # Password is specified as a BCrypt hash. Use htpasswd -B to generate.
  "lava-admin":
    password: "$2y$05$Eyf7EMC3aMX8DFXu95aHkeSRfRyEgsM2FFUW5cU00ZPDNkYEQIMni"
  "": {}  # Allow anonymous (no "docker login") access.

acl:
  - match: {account: "lava-admin"}
    actions: ["*"]
    comment: "lava-admin has full access to everything."
  - match: {account: "", type: "registry", name: "catalog"}
    actions: ["*"]
    comment: "Anonymous users can query the catalog."
  - match: {account: ""}
    actions: ["pull"]
    comment: "Anonymous users can pull everything."
  # Access is denied by default.
```

The anonymous pull works properly, I even once changed it so the entire acl section was as below, but still catalog queries are denied with same error message.
```
acl:
  - match: {account: ""}
    actions: ["*"]
    comment: "Anonymous users have full access to everything."
```
Thanks for any help.

**Comment by mrueg** [comment]
@rojer can you reopen this one? It seems like the rule doesn't match as expected for anonymous users trying to access the catalog?

**Comment by tamasgal** [comment]
I have the same issue, I cannot access the catalog from the browser or via `curl` no matter if I use anonymous access or an authenticated user (as far as I understood I'd need a bearer token anyways).

Are there any updates on making the catalog accessible for anonymous users?

**Comment by laopisai** [comment]
I have the same issue, all endpoints work except catalog

```
acl:
  - match: {account: "/.+/", type: "registry", name: "catalog"}
    actions: ["*"]
```

Here's what I found in the response header

```
www-authenticate: Bearer realm="https://registry/auth",service="docker-registry",scope="registry:catalog:*",error="insufficient_scope"
```

**Comment by spiarh** [comment]
I was having the same issue and fixed by adding the "anonymous" user under `users`

```
users:
  "": {}  # Allow anonymous (no "docker login") access.
```

This gives me the following full configuration where admin can do everything and anonymous user can query the catalog and pull images:

```
server:
  addr: ":5001"
  certificate: "/config/secrets/server.crt"
  key: "/config/secrets/server.key"

token:
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900

users:
  "admin":
    password: "$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC"  # badmin
  "": {}  # Allow anonymous (no "docker login") access.

acl:
  - match: {account: "admin"}
    actions: ["*"]
    comment: "Full access to everything."
  - match: {account: "", type: "registry", name: "catalog"}
    actions: ["*"]
    comment: "Anonymous can query the catalog"
  - match: {account: ""}
    actions: ["pull"]
    comment: "Anonymous can pull everything"
```

I hope that helps :wink:
