### ISSUE TITLE
No access for loggined users to anonymouse repos

### ISSUE THREAD

**Issue by Telonko** [cesanta/docker_auth#396]
If you are not logged in you have access to the repo "example".
If you logged in you have access only to repos in the rules.
```
acl:
  - match: {name: "${labels:read-only-access}"}
    actions: ["pull"]
  - match: {account: "", name: "example"}
    actions: ["pull"]
    comment: "List of repos for Anonymous users"
```
