### ISSUE TITLE
SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by bengivre** [cesanta/docker_auth#404]
I've been using docker_auth with Github for a while now. 
For some reason, after a power outage , docker_auth can't start anymore..  Not sure why. 

If I remove the the github part, the server starts. If I keep it, I get SIGSEGV 

Thanks a lot for your help 

**Here is my github config part:** 

```
github_auth:
  organization: "360metrics"
  client_id: "my_id"
  client_secret: "my_secret"
  token_db: /data/tokens.db
  registry_url: "https://registry.example.com"
```

**Here is the log :** 

```
I0530 04:35:14.670783       1 main.go:248] docker_auth  build
I0530 04:35:14.707911       1 main.go:61] Config from /config/auth_config.yml (2 users, 7 ACL static entries)
I0530 04:35:14.708039       1 acl.go:109] Created ACL Authorizer with 7 entries
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xff954e]

goroutine 1 [running]:
github.com/cesanta/docker_auth/auth_server/authn.NewTokenDB(0x7f091de185b8?)
	/build/authn/tokendb_level.go:84 +0xe
github.com/cesanta/docker_auth/auth_server/authn.NewGitHubAuth(0xc0000b7220)
	/build/authn/github_auth.go:169 +0xf1
github.com/cesanta/docker_auth/auth_server/server.NewAuthServer(0xc000176d88)
	/build/server/server.go:100 +0x69e
main.ServeOnce(0xc000176d88, {0x7fff075e8f64?, 0xc000467b90?})
	/build/main.go:62 +0x118
main.(*RestartableServer).Serve(0xc0000efee8, 0x17?)
	/build/main.go:180 +0x25
main.main()
	/build/main.go:261 +0x256
```
