### ISSUE TITLE
Question on ACL Order

### ISSUE THREAD

**Issue by dpetzel** [cesanta/docker_auth#56]
I'm not sure if this intended, a bug, or I'm doing something wrong. I'm attempting configure some ACLs and I've used the reference example as a starting point.

When I have this configuration:
```
- match:
    account: /.+/
  actions:
  - pull
  comment: All logged in users can pull all images.
- match:
    account: /.+/
    name: ${account}/*
  actions:
  - push
  - pull
  comment: All logged in users can push all images that are in a namespace beginning
    with their name
```
As you would expect I am able to pull just fine, however pushing to a repo in the users namespace It tosses an `unauthorized: authentication required`.

However this works (its exactly the same, just the ordering has been flipped):
```
- match:
    account: /.+/
    name: ${account}/*
  actions:
  - push
  - pull
  comment: All logged in users can push all images that are in a namespace beginning
    with their name
- match:
    account: /.+/
  actions:
  - pull
  comment: All logged in users can pull all images.
```

So it feels like the first ACL that matches is returned, and the rest are not applied. Do I need to do anything to make it honor both regardless of order?

Thanks
