### ISSUE TITLE
Is there an example on how to use the docker_auth server to get a token?

### ISSUE THREAD

**Issue by spsiddarthan** [cesanta/docker_auth#92]
I had docker_auth set up on my instance but when I hit the server to get a token (to subsequently make requests to the v2 end point of my registry) I got an auth failed error. 

Perhaps I'm doing something obviously stupid. Would really appreciate it if someone could provide me with an example.

**Comment by carsonoid** [comment]
You don't usually hit the auth_server directly.  You should configure your
registry to forward clients to the auth server.

Ex:
```yaml
auth:
  token:
    realm: "https://my.registry.com/auth"
    service: "Docker registry"
    issuer: "Auth Service"
    rootcertbundle: "/ssl/server.pem"

```

Then you use `docker login` to log in to the registry and all push/pulls
with authenticated against the server defined in `realm`.  Note also that
the `issuer` field in the registry much match that in the docker_auth's
config.

**Comment by carsonoid** [comment]
You don't usually hit the auth_server directly.  You should configure your
registry to forward clients to the auth server.

Ex:
```yaml
auth:
  token:
    realm: "https://my.registry.com/auth"
    service: "Docker registry"
    issuer: "Auth Service"
    rootcertbundle: "/ssl/server.pem"

```

Then you use `docker login` to log in to the registry and all push/pulls
with authenticated against the server defined in `realm`.  Note also that
the `issuer` field in the registry much match that in the docker_auth's
config.

There is a fairly good article describing the whole process [here](https://the.binbashtheory.com/creating-private-docker-registry-2-0-with-token-authentication-service/)
