### ISSUE TITLE
ldap authentication failed if password is not crypt

### ISSUE THREAD

**Issue by jay1xiong** [cesanta/docker_auth#96]
ldap authentication failed if the password is not crypt. clear and ssha are both failing ldap authentication. My docker-auth configuration is as follows:

curl -H "Authorization: Basic $(echo "mozart:password" | base64)" -vk "https://127.0.0.1:5001/auth?service=Docker%20registry&scope=registry:catalog:*"

is causing the authentication issue. Directly login form docker login works fine.

```
# . See reference.yml for explanation for explanation of all options.
#
#  auth:
#    token:
#      realm: "https://127.0.0.1:5001/auth"
#      service: "Docker registry"
#      issuer: "Acme auth server"
#      rootcertbundle: "/path/to/server.pem"

server:
  addr: ":5001"
  certificate: "/certs/auth.crt"
  key: "/certs/auth.key"

token:
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900

# LDAP authentication.
# Authentication is performed by first binding to the server, looking up the user entry
# by using the specified filter, and then re-binding using the matched DN and the password provided.
ldap_auth:
  addr: "10.0.2.110:389"
  #tls: true
  # In case bind DN and password is required for querying user information,
  # specify them here. Plain text password is read from the file.
  bind_dn: "cn=admin,dc=verilume,dc=com"
  # Make sure you remove newlines and carriage returns from the password file.
  bind_password_file: /tmp/ldap_password.txt.clean
  # User query settings. ${account} is expanded from auth request 
  #base: "ou=polarbear.com,dc=verilume,dc=com"
  base: "dc=verilume,dc=com"
  filter: "(&(cn=${account})(objectClass=inetOrgPerson))"

users:
  # Password is specified as a BCrypt hash. Use htpasswd -B to generate.
  "admin":
    password: "$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC"  # badmin
  "test":
    password: "$2y$05$WuwBasGDAgr.QCbGIjKJaep4dhxeai9gNZdmBnQXqpKly57oNutya"  # 123

acl:
  # Admin has full access to everything.
  - match: {account: "admin"}
    actions: ["*"]

  # User "user" can pull stuff.
  - match: {account: "test"}
    actions: ["pull"]

  # This will allow authenticated users to pull/push
  - match:
      account: /.+/
    actions: ['*']

  # The user "serviceaccount" (from LDAP) may not perform any docker actions
  # like push or pull.
  - match: {account: "admin"}
    actions: []

```

Successful Authentication (crypt):

```
jenkins@ubuntu-docker:~/docker-registry-setup$ curl -H "Authorization: Basic $(echo "johndoe@polarbear.com:password" | base64)" -vk "https://127.0.0.1:5001/auth?service=Docker%20registry&scope=registry:catalog:*"
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 5001 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: C=DE; ST=Example State; L=Example City; O=Example Company; OU=Example Organizational Unit; CN=auth.example.com; emailAddress=admin@auth.example.com
* 	 start date: 2015-10-26 11:03:48 GMT
* 	 expire date: 2016-10-25 11:03:48 GMT
* 	 issuer: C=DE; ST=Example State; L=Example City; O=Example Company; OU=Example Organizational Unit; CN=auth.example.com; emailAddress=admin@auth.example.com
* 	 SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /auth?service=Docker%20registry&scope=registry:catalog:* HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:5001
> Accept: */*
> Authorization: Basic am9obmRvZUBwb2xhcmJlYXIuY29tOnBhc3N3b3JkCg==
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Fri, 06 May 2016 10:51:29 GMT
< Content-Length: 1122
< 
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjVGS1k6WVoyMjpSRk9UOlJFWjM6REVNVDpSQ1Y3OkRNTVU6Wk5JSDpVWTZROkM3VVI6WVZDWDpMSjRDIn0.eyJpc3MiOiJBY21lIGF1dGggc2VydmVyIiwic3ViIjoiam9obmRvZUBwb2xhcmJlYXIuY29tIiwiYXVkIjoiRG9ja2VyIHJlZ2lzdHJ5IiwiZXhwIjoxNDYyNTMyNzg5LCJuYmYiOjE0NjI1MzE4NzksImlhdCI6MTQ2MjUzMTg4OSwianRpIjoiNzA3ODEyNjYzNDk1OTYxNTIzMyIsImFjY2VzcyI6W3sidHlwZSI6InJlZ2lzdHJ5IiwibmFtZSI6ImNhdGFsb2ciLCJhY3Rpb25zIjpbIioiXX1dfQ.mL2_7bhg1h6SefSFZ7gAlPgFW-PymAC4qj29qos4N3P6VWoQeOYwnd9p2Pr2diFC3Ohwxj4yQ96TagMJd6wV3pXEzEiuQYLNwIvH02TUSDYOM1CU_O3PBSXnj_6jOx6C52QJID3RAdz7L7yyylCC8MeSI_Ey5eqxmhqHSvPnBAC0krvvVLQn007tNG380W2SykUJEl9Wco3vBZ-HK4RPJX7IHtZTNabwcdQIHZzEyO0argnxO_r-rwv2ZZFA3pl8Abj5IvSG2h2VAQGL3IpHvr2QXcWdSqIp-hlzPE_1ynMYfvalrUkz5Cz1lxNi0K_O2VSR79aZT8Nb4HkJW8upysnW3CIUZwJYtyrxsRxH7jzGao0jvspHHsI7DKDB8DVBe57zVLgr7X7KhYl0sVMPgIh1M4w9N9v-6CxlRvqN4lr8445vTlw_sRKVdfbchCbBu0V1NAAMC_GZ0_4Ci0qPcy9mulv2oM23KN1KyTgeCv6YBySuoK56v2HzFGck_sYtcc5hRmrqtMrmoqA2ivwsvtFTGLY6fTvn6X6kwQ4uTCmbGhlZvZH00cnfNvyQYmtAq5haXLikLEv* Connection #0 to host 127.0.0.1 left intact
ExqCLWzpFJkpzRkmLk_fi6g3Hf20NE7rbdxlfqgxd4TJauG0I7mWH0wcFoflEXTJ0copTK5Ji7PXjXKj7UEQjWAaJBU3eTNE"}

```

Failed Authentication (ssha):

```
jenkins@ubuntu-docker:~/docker-registry-setup$ curl -H "Authorization: Basic $(echo "johndoe@polarbear.com:password" | base64)" -vk "https://127.0.0.1:5001/auth?service=Docker%20registry&scope=registry:catalog:*"
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 5001 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: C=DE; ST=Example State; L=Example City; O=Example Company; OU=Example Organizational Unit; CN=auth.example.com; emailAddress=admin@auth.example.com
* 	 start date: 2015-10-26 11:03:48 GMT
* 	 expire date: 2016-10-25 11:03:48 GMT
* 	 issuer: C=DE; ST=Example State; L=Example City; O=Example Company; OU=Example Organizational Unit; CN=auth.example.com; emailAddress=admin@auth.example.com
* 	 SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /auth?service=Docker%20registry&scope=registry:catalog:* HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:5001
> Accept: */*
> Authorization: Basic am9obmRvZUBwb2xhcmJlYXIuY29tOnBhc3N3b3JkCg==
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Fri, 06 May 2016 10:52:47 GMT
< Content-Length: 93
< 
Authentication failed (authn #2 returned error: LDAP Result Code 49 "Invalid Credentials": )
* Connection #0 to host 127.0.0.1 left intact
```
