### ISSUE TITLE
Failed to load config during startup private registry server with LDAP auth

### ISSUE THREAD

**Issue by Bart187** [cesanta/docker_auth#99]
Hi All,

I have issue on RHEL7 with the image or configuration. When I'm trying to run the 

    docker run --rm -it --name docker_auth -p 5001:5001 -v /data/docker_registry/docker/docker_auth-master:/config:ro -v /var/log/docker_auth:/logs cesanta/docker_auth:stable /data/docker_registry/docker/docker_auth-master/docker-compose.yml

I'm getting this error:

    F0601 10:42:30.862161       1 main.go:167] Failed to load config: could not read /data/docker_registry/docker/docker_auth-master/docker-compose.yml: open /data/docker_registry/docker/docker_auth-master/docker-compose.yml: no such file or directory

File there is in /data/docker_registry/docker/docker_auth-master:
```
     [root@D-L-TOOLS docker_auth-master]# ll
     total 32
     drwx------. 6 root root  4096 Apr  8 13:10 auth_server
     -rwxrwxrwx. 1 root root  1473 Jun  1 13:59 docker-compose.yml
     drwx------. 2 root root  4096 Apr  8 13:10 docs
     drwx------. 2 root root  4096 Apr  8 13:10 examples
     -rw-------. 1 root root 10173 Apr  8 13:10 LICENSE
     -rw-------. 1 root root  2928 Apr  8 13:10 README.md
```

But is could not be read. I've even push it to /tmp folder (moved the configuration there and path as well), but still without success... Do You know what could be wrong?

docker-compose.yml configuration from my server:

 
```
    server:
    
      addr: :5001
      certificate: /data/docker_registry/docker/certs/docker-registry.crt
      key: /data/docker_registry/docker/certs/docker-registry.key
    token:
     issuer: Acme auth server
     expiration: 900
    ldap_auth:
      # Addr is the hostname:port or ip:port
      addr: "ldaps://ldap.xxxxxxxx:636/OU=xxxx,DC=xxxx,DC=local?sAMAccountName?sub?(&
(memberOf:1.2.840.113556.1.4.1941:=cn=xxxxx,OU=xxxxxxx,OU=Groups,OU=GLOB000,OU=Global,OU=xxxx,DC=xxxx,DC=local)
(objectClass=person))" SSL
      # Setup tls connection method to be
      # "" or "none": the communication won't be encrypted
      # "always": setup LDAP over SSL/TLS
      # "starttls": sets StartTLS as the encryption method
      tls: always
      # set to true to allow insecure tls
      insecure_tls_skip_verify: false
      # In case bind DN and password is required for querying user information,
      # specify them here. Plain text password is read from the file.
      bind_dn: "CN=xxxxxxxx,OU=Service_Accounts,OU=Admins,OU=GLOB000,OU=Global,OU=Root,DC=xxxxx,DC=local"
      bind_password_file: xxxxxx
     # User query settings. ${account} is expanded from auth request
     #base: o=example.com
     #filter: (&(uid=${account})(objectClass=person))
    acl:
      # This will allow authenticated users to pull/push
     - match:
     account: /.+/ 
     actions: ['*']
    
    
    
    registry:
      restart: always
      image: registry:2
     #  hostname: "Registry_docker"
      environment:
        - REGISTRY_DELETE_ENABLED=true
      volumes:
        - /data/docker_registry:/var/lib/registry
      ports:
        - 5000:5000
```

############################################################################

My docker version is:

    [root@D-L-TOOLS docker_auth-master]# docker version
    Client:
     Version:      1.11.1
     API version:  1.23
     Go version:   go1.5.4
     Git commit:   5604cbe
     Built:        Wed Apr 27 00:34:42 2016
     OS/Arch:      linux/amd64
    
    Server:
     Version:      1.11.1
     API version:  1.23
     Go version:   go1.5.4
     Git commit:   5604cbe
     Built:        Wed Apr 27 00:34:42 2016
     OS/Arch:      linux/amd64

**Comment by carsonoid** [comment]
So there are a few issues here:

1. You should name your docker_auth config file something like `auth_config.yml` instead of `docker-compose.yml`. [docker-compose](https://docs.docker.com/compose/) is something completely separate from this project.
1. As per the [docs](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems): the second portion of a volume mount option will dictate the path in the container that the mounted volume will reside at.

So your command should be:

```bash
docker run --rm -it --name docker_auth -p 5001:5001 -v /data/docker_registry/docker/docker_auth-master:/config:ro -v /var/log/docker_auth:/logs cesanta/docker_auth:stable docker-compose.yml
```

And, if you change your config file name to avoid confusion then a more idealized version of the command would be:

```bash
docker run --rm -it --name docker_auth -p 5001:5001 -v /data/docker_registry/docker/docker_auth-master/auth_config.yml:/config/auth_config.yml:ro -v /var/log/docker_auth:/logs cesanta/docker_auth:stable
```

Breaking down the changes:

1. Using a more appropriate name for the config file.
1. `-v /data/docker_registry/docker/docker_auth-master:/config:ro` becomes ` -v /data/docker_registry/docker/docker_auth-master/docker_auth.yml:/config/auth_config.yml:ro` By doing this you mount a specific file in your host to a specific location in the container. It's likely that your container doesn't need access to the entire
1. All options after the name of the image (`cesanta/docker_auth:stable`) are removed since the default command will already be looking in the right place for our mounted config file. This can be found by looking at the [Dockerfile](https://github.com/cesanta/docker_auth/blob/master/auth_server/Dockerfile#L4) for the image.

**Comment by carsonoid** [comment]
I'm also guessing that there are other errors in your config. Can you please paste it with code formatting so that it can be more easily reviewed?

**Comment by Bart187** [comment]
Hi,

I have checked the conf file and it seems that there is still something wrong.

I have started the registry:

`docker run -d -p 5000:5000 --restart=always --name Docker_registry -v /data/docker_registry:/var/lib/registry -v /etc/docker/certs.d:/etc/docker/certs.d -e REGISTRY_HTTP_TLS_CERTIFICATE=/etc/docker/certs.d/docker.crt  -e REGISTRY_HTTP_TLS_KEY=/etc/docker/certs.d/docker.key registry:2`

And it's working ok. I can push and pull images there.

With this command I started the auth server (as You suggested):

`docker run --rm -it --name docker_auth -p 5001:5001 -v /data/docker_registry/docker/backup/cesanta/docker_auth-master/auth_config.yml:/config/auth_config.yml:ro -v /var/log/docker_auth:/logs cesanta/docker_auth:stable`

I don't have previous error, but there is still something wrong:

`F0608 12:03:34.968175       1 main.go:167] Failed to load config: could not parse config: yaml: line 8: did not find expected key`

My configuration looks like:

```
server:
 addr: :5001
 certificate: /etc/docker/certs.d/docker.crt
 key: /etc/docker/certs.d/docker.key
token:
 issuer: Acme auth server
 expiration: 900
ldap_auth:
addr: "ldaps://ldap.xxxxxxxxxx.com:636/OU=xxxx,DC=xxxx,DC=local?sAMAccountName?sub?(&(memberOf:1.2.840.113556.1.4.1941:=cn=xxxxxxxxxx,OU=xxxx,OU=xxxxxxx,OU=xxxxxx,OU=xxxxxxl,OU=xxxxx,DC=xxxxxt,DC=xxxx)(objectClass=person))" SSL;
  tls: always
  insecure_tls_skip_verify: false
  bind_dn: "CN=xxxxxxxx,OU=xxxxxxx,OU=xxxxxx,OU=xxxxx,OU=xxxxx,OU=xxxxx,DC=xxxx,DC=xxxxx"
  bind_password_file: xxxxxxx
acl:
  - match:
      account: /.+/
    actions: ['*']
```

Do You know what could be wrong with LDAP conf? Seems that addr is in wrong format, but tried this at nginx conf already and it was working well.

**Comment by rojer** [comment]
you need to indent the line below `ldap_auth:` (line 8). make `addr:` line up with `tls:`.

**Comment by Bart187** [comment]
In original file addr: line is in the same place as tls. On the above formatting it seems to be in the same place as acl or ldap_auth.

seems that is not an issue here...

**Comment by rojer** [comment]
there's trailing "SSL" on line 8, outside quotes.

**Comment by Bart187** [comment]
I've got running configuration with that on reverse proxy configuration, but I changed it just to check:

```
server:
 addr: :5001
 certificate: /etc/docker/certs.d/docker.crt
 key: /etc/docker/certs.d/docker.key
token:
 issuer: Acme auth server
 expiration: 900
ldap_auth:
 addr: "ldaps://ldap.xxxxxxxxxx.com:636/OU=xxxx,DC=xxxx,DC=local?sAMAccountName?sub?(&(memberOf:1.2.840.113556.1.4.1941:=cn=xxxxxxxxxx,OU=xxxx,OU=xxxxxxx,OU=xxxxxx,OU=xxxxxxl,OU=xxxxx,DC=xxxxxt,DC=xxxx)(objectClass=person)) SSL"
  tls: always
  insecure_tls_skip_verify: false
  bind_dn: "CN=xxxxxxxx,OU=xxxxxxx,OU=xxxxxx,OU=xxxxx,OU=xxxxx,OU=xxxxx,DC=xxxx,DC=xxxxx"
  bind_password_file: xxxxxxx
acl:
  - match:
      account: /.+/
    actions: ['*']
```

But I got the same:

```
docker run --rm -it --name docker_auth -p 5001:5001 -v /data/docker_registry/docker/backup/cesanta/docker_auth-master/auth_config.yml:/config/auth_config.yml:ro -v /var/log/docker_auth:/logs cesanta/docker_auth:stable
F0609 12:51:28.553781       1 main.go:167] Failed to load config: could not parse config: yaml: line 8: did not find expected key
```
